ARG NODE_VERSION
FROM node:${NODE_VERSION} as builder
USER node
ENV NODE_ENV=production
COPY . /home/node
WORKDIR /home/node
RUN set -ex; \
    npm install; \
    npm run build
EXPOSE 3000
CMD ["npm", "start"]