version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 18
        NODE_ENV: production
    restart: unless-stopped
    ports:
      - 