version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: '3.10'
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=app
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 5000:5000
  
  db:
    image: mariadb:10
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_USER=app
      - MARIADB_DATABASE=app
      - MARIADB_PASSWORD=app
    ports:
      - 3306:3306
    volumes:
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql

volumes:
  db-data: