ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}
RUN useradd --create-home --shell /bin/false \
    --system --home-dir /app app
WORKDIR /app
COPY --chown=app:app ./src/requirements.txt /app/
RUN pip install -r /app/requirements.txt; \
    python -m compileall; \
    python -m compileall .
COPY --chown=app:app ./src/ /app/
USER app
EXPOSE 5000
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "main:app"]